### ISSUE TITLE
Error message on every action

### ISSUE THREAD

**Issue by antonjazzsax** [carrus2049/reaper_SM_tweaker#5]
Getting following error message for every type of action, regardless of the marker's context:

API_SM_move_zoom_dep_forward.lua:2: attempt to concatenate a nil value (local 'script_path')

**Comment by carrus2049** [comment]
I assume you're on Windows and path delimiter is not handled correctly, I fixed this to the latest commit, plz update and see how it goes!

**Comment by antonjazzsax** [comment]
Ok, the error message is gone now. So this one seems to be sorted. Great!. Will see, if any other error messages appears along the way

**Comment by smandrap** [comment]
You can change this:
```lua
local script_path = nil
if reaper.GetOS() ==  "Win32" or reaper.GetOS() == "Win64" then
    script_path = debug.getinfo(1).source:match("@?(.*\\)")
else
    script_path = debug.getinfo(1).source:match("@?(.*/)")
end
```

To

```lua
local script_path = debug.getinfo(1).source:match(("@?(.*%s)"):format(package.config:sub(1, 1)))
```

Where `package.config:sub(1, 1)` will return the os separator

**Comment by carrus2049** [comment]
> You can change this:
> 
> ```lua
> local script_path = nil
> if reaper.GetOS() ==  "Win32" or reaper.GetOS() == "Win64" then
>     script_path = debug.getinfo(1).source:match("@?(.*\\)")
> else
>     script_path = debug.getinfo(1).source:match("@?(.*/)")
> end
> ```
> 
> To
> 
> ```lua
> local script_path = debug.getinfo(1).source:match(("@?(.*%s)"):format(package.config:sub(1, 1)))
> ```
> 
> Where `package.config:sub(1, 1)` will return the os separator

Well that is brilliant, thanks alot!

**Comment by antonjazzsax** [comment]
Awesome. Thanks a lot
