### ISSUE TITLE
Mousewheel action based on zoom dependant action

### ISSUE THREAD

**Issue by antonjazzsax** [carrus2049/reaper_SM_tweaker#6]
The great enhancement would be to have the zoom dependant actions assignable to mouse center wheel. Is it possible?

**Comment by carrus2049** [comment]
According to [this post](https://forum.cockos.com/showthread.php?t=271067) it most certainly is! I'll add that to the  next update alongside the power undo function.

And whats better is that it's possible to assign 2 way adjust action assigned to stuff like rotary encoder too. Well thats pretty inspiring!

**Comment by carrus2049** [comment]
added in 0.0.3
