### ISSUE TITLE
"For midi encoder, besides adding shortcut, set MIDI CC to Relative 2 mode" - Explanation needed!

### ISSUE THREAD

**Issue by antonjazzsax** [carrus2049/reaper_SM_tweaker#9]
Can you please add into the description, where is this setting to be adjusted? I could find the "Revert" argument line true/false.
But I couldn't find the  line related to MIDI CC Mode in the code. Or is this setting to be adjusted on the controller itself?

**Comment by carrus2049** [comment]
In 0.0.3, the revert can be set in [here](https://github.com/carrus2049/reaper_SM_tweaker/blob/a85e7daeaae8f14eab99be0682453e7d9419be8d/src/API_SM_move_abs_val_2way.lua#L7) and [here](https://github.com/carrus2049/reaper_SM_tweaker/blob/a85e7daeaae8f14eab99be0682453e7d9419be8d/src/API_SM_move_zoom_dep_2way.lua#L7), yea that should be surely added to the description!

The MIDI CC Mode setting lies in the short cut edit window:
![WeChatWorkScreenshot_a11606c2-3e60-4347-ba75-81550e738436](https://github.com/carrus2049/reaper_SM_tweaker/assets/70931300/bc8801a2-7418-41bc-8340-4d260359a6cc)
